### ISSUE TITLE
[depends/conf]Add comments for each env vars when generate default.yml

### ISSUE THREAD

**Issue by simonerom** [machinefi/w3bstream#192]
I've added those that I could guess the meaning for. Please provide an explanation for settings where they've been marked with "???". 

```yaml
# MQTT client settings

## Set the maximum time interval allowed between messages before being disconnected
SRV_APPLET_MGR__BROKER__Keepalive: 3h
## ??? Set the MQTT Quality of Service (please explain possible values and how they map to the values QoS 0-1-2 of the standard)
SRV_APPLET_MGR__BROKER__QoS: ONCE
## Ask the MQTT server to retain the most recent message for a topic
SRV_APPLET_MGR__BROKER__RetainPublish: "false"
## Specifyi a retry Interval for failed connections to the MQTT broker
SRV_APPLET_MGR__BROKER__Retry_Interval: 3s
## Specify the maximum number of connection retries
SRV_APPLET_MGR__BROKER__Retry_Repeats: "3"
## MQTT broker endpoint
SRV_APPLET_MGR__BROKER__Server: mqtt://127.0.0.1:1883
## Connection timeout
SRV_APPLET_MGR__BROKER__Timeout: 3s

# W3bstream settings

## ??? (is this the folder where applets are stored?)
SRV_APPLET_MGR__CONFIG__ResourceRoot: ./asserts
## xx is this the makimum size in bytes of an applet?
SRV_APPLET_MGR__CONFIG__UploadLimit: "104857600"

# Blockchain settings

## Blockchain gateway endpoint
SRV_APPLET_MGR__ETHCLIENTCONFIG__ChainEndpoint: "https://babel-api.testnet.iotex.io/"
## Private key used for transactions sent by the host
SRV_APPLET_MGR__ETHCLIENTCONFIG__PrivateKey: ""

# Login token settings

## Login token expiration time
SRV_APPLET_MGR__JWT__ExpIn: 1h
## Login token issuer
SRV_APPLET_MGR__JWT__Issuer: "srv-applet-mgr"
## ??? Please explain what is this and what value should be used
SRV_APPLET_MGR__JWT__SignKey: "xxxx"

# Log settings

## Log format
SRV_APPLET_MGR__LOG__Format: JSON
## Log level
SRV_APPLET_MGR__LOG__Level: DEBUG
## Log name
SRV_APPLET_MGR__LOG__Name: "srv-applet-mgr"
## ???
SRV_APPLET_MGR__LOG__ReportCaller: "false"
## ??? what are possible values here?
SRV_APPLET_MGR__LOG__Output: ALWAYS

# DB settings

## ??? what happens after 1h?
SRV_APPLET_MGR__PGCLI__ConnMaxLifetime: 1h
## DB connection string
SRV_APPLET_MGR__PGCLI__Master: postgres://test_user:test_passwd@127.0.0.1:5432/test?sslmode=disable
## ???
SRV_APPLET_MGR__PGCLI__PoolSize: "10"
## ???
SRV_APPLET_MGR__PGCLI__Retry_Interval: 3s
## ???
SRV_APPLET_MGR__PGCLI__Retry_Repeats: "3"
## ???
SRV_APPLET_MGR__PGCLI__Slave: ""

# API server settings

## Enable debug log 
SRV_APPLET_MGR__SERVER__Debug: "true"
## API server port
SRV_APPLET_MGR__SERVER__Port: "8888"
## API specs
SRV_APPLET_MGR__SERVER__Spec: ./swagger.json

## xxx is this duplicated of SRV_APPLET_MGR__CONFIG__UploadLimit above?
SRV_APPLET_MGR__UPLOADCONFIG__FileSizeLimit: "104857600"
## xxx is this duplicated of SRV_APPLET_MGR__CONFIG__ResourceRoot above?
SRV_APPLET_MGR__UPLOADCONFIG__Root: ./asserts
```
